"""
Decision Engine — Core AI reasoning loop.
Fuses rule-based signals with LLM analysis to produce trade proposals.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional

from src.ai.llm_client import LLMClient
from src.ai.prompts import (
    MARKET_ANALYSIS_PROMPT,
    POSITION_REVIEW_PROMPT,
    SYSTEM_TRADE_ANALYST,
    TRADE_RISK_ASSESSMENT_PROMPT,
    SYSTEM_RISK_ASSESSOR,
)
from src.ai.signal_generator import RuleSignal, SignalGenerator
from src.data.indicators import IndicatorEngine
from src.data.market_state import MarketState

logger = logging.getLogger(__name__)


@dataclass
class TradeProposal:
    """A proposed trade generated by the AI decision engine."""
    symbol: str
    action: str                     # BUY / SELL
    qty: Optional[int] = None       # Filled by position sizer
    order_type: str = "market"      # market / limit
    limit_price: Optional[float] = None
    confidence: float = 0.0
    reasoning: str = ""
    risk_level: str = "MEDIUM"      # LOW / MEDIUM / HIGH
    rule_signal_score: float = 0.0  # From rule-based signal generator
    source: str = "ai"              # ai / rule / hybrid
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "action": self.action,
            "qty": self.qty,
            "order_type": self.order_type,
            "limit_price": self.limit_price,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "risk_level": self.risk_level,
            "rule_signal_score": self.rule_signal_score,
            "source": self.source,
            "timestamp": self.timestamp.isoformat(),
        }


class DecisionEngine:
    """
    Core reasoning loop:
    1. Receive MarketState + PortfolioState
    2. Generate rule-based signals (confluence)
    3. Pass actionable signals + context to LLM
    4. LLM returns structured TradeProposals
    5. Route proposals to Risk Manager
    """

    def __init__(self):
        self._llm = LLMClient()
        self._signal_gen = SignalGenerator()
        self._indicator_engine = IndicatorEngine()
        self._llm_available = False

    def check_llm(self) -> bool:
        """Check if LLM is available and cache the result."""
        self._llm_available = self._llm.is_available()
        return self._llm_available

    def analyze(
        self,
        market_state: MarketState,
        portfolio_summary: str,
        existing_positions: List[str],
    ) -> List[TradeProposal]:
        """
        Run the full analysis pipeline and return trade proposals.

        Args:
            market_state: Current market state with indicators.
            portfolio_summary: Human-readable portfolio summary for LLM context.
            existing_positions: List of symbols currently held.
        """
        proposals: List[TradeProposal] = []

        # Step 1: Rule-based signals from indicators
        indicator_snapshots = {
            sym: state.indicators
            for sym, state in market_state.symbols.items()
            if state.indicators is not None
        }
        rule_signals = self._signal_gen.generate_batch(indicator_snapshots)
        actionable = self._signal_gen.filter_actionable(rule_signals, min_score=0.2)

        logger.info(
            "Rule signals: %d total, %d actionable (score >= 0.2)",
            len(rule_signals), len(actionable),
        )

        # Log top signals
        for sym, sig in sorted(
            actionable.items(), key=lambda x: abs(x[1].score), reverse=True
        )[:5]:
            logger.info("  %s: %s (score=%.3f)", sym, sig.strength.value, sig.score)

        # Step 2: LLM analysis (if available)
        if self._llm_available:
            try:
                llm_proposals = self._llm_analyze(
                    market_state, portfolio_summary, existing_positions, rule_signals
                )
                proposals.extend(llm_proposals)
            except Exception as e:
                logger.error("LLM analysis failed, falling back to rule-based: %s", e)
                proposals.extend(
                    self._rule_only_proposals(actionable, existing_positions)
                )
        else:
            logger.warning("LLM unavailable, using rule-based signals only")
            proposals.extend(
                self._rule_only_proposals(actionable, existing_positions)
            )

        return proposals

    def _llm_analyze(
        self,
        market_state: MarketState,
        portfolio_summary: str,
        existing_positions: List[str],
        rule_signals: Dict[str, RuleSignal],
    ) -> List[TradeProposal]:
        """Send market state to LLM and parse trade proposals."""

        # Build a focused market state with actionable symbols first
        # to keep the LLM response within token limits
        focused_state = market_state.focused_copy(
            rule_signals=rule_signals, max_symbols=15
        )

        # Build the user prompt
        user_prompt = MARKET_ANALYSIS_PROMPT.format(
            market_state=focused_state.to_llm_context(max_symbols=15),
            portfolio_state=portfolio_summary,
        )

        # Call LLM
        try:
            response = self._llm.analyze_json(
                system_prompt=SYSTEM_TRADE_ANALYST,
                user_prompt=user_prompt,
            )
        except (ConnectionError, ValueError) as e:
            logger.error("LLM call failed: %s", e)
            raise  # Re-raise so caller can fall back to rule-based signals

        # Parse response into TradeProposals
        proposals = []
        signals = response.get("signals", [])

        for sig in signals:
            symbol = sig.get("symbol", "").upper()
            action = sig.get("action", "HOLD").upper()

            if action == "HOLD":
                continue

            # Cross-reference with rule-based signal
            rule_sig = rule_signals.get(symbol)
            rule_score = rule_sig.score if rule_sig else 0.0

            proposal = TradeProposal(
                symbol=symbol,
                action=action,
                confidence=float(sig.get("confidence", 0.0)),
                reasoning=sig.get("reasoning", ""),
                risk_level=sig.get("risk_level", "MEDIUM"),
                order_type=sig.get("suggested_order_type", "market"),
                limit_price=sig.get("suggested_limit_price"),
                rule_signal_score=rule_score,
                source="hybrid" if rule_sig else "ai",
            )
            proposals.append(proposal)

        logger.info(
            "LLM produced %d proposals (market assessment: %s)",
            len(proposals),
            response.get("market_assessment", "N/A")[:100],
        )

        return proposals

    def _rule_only_proposals(
        self,
        actionable: Dict[str, RuleSignal],
        existing_positions: List[str],
    ) -> List[TradeProposal]:
        """Generate proposals from rule-based signals only (LLM fallback)."""
        proposals = []

        for sym, sig in sorted(
            actionable.items(), key=lambda x: abs(x[1].score), reverse=True
        )[:5]:
            if sig.score > 0.3 and sym not in existing_positions:
                proposals.append(TradeProposal(
                    symbol=sym,
                    action="BUY",
                    confidence=min(sig.score, 0.9),
                    reasoning="; ".join(sig.details[:3]),
                    risk_level="LOW" if sig.score > 0.5 else "MEDIUM",
                    rule_signal_score=sig.score,
                    source="rule",
                ))
            elif sig.score < -0.3 and sym in existing_positions:
                proposals.append(TradeProposal(
                    symbol=sym,
                    action="SELL",
                    confidence=min(abs(sig.score), 0.9),
                    reasoning="; ".join(sig.details[:3]),
                    risk_level="LOW" if sig.score < -0.5 else "MEDIUM",
                    rule_signal_score=sig.score,
                    source="rule",
                ))

        return proposals

    def review_positions(
        self,
        positions_summary: str,
        market_state: MarketState,
    ) -> Dict:
        """Ask the LLM to review open positions and suggest actions."""
        if not self._llm_available:
            return {"position_reviews": [], "portfolio_summary": "LLM unavailable"}

        user_prompt = POSITION_REVIEW_PROMPT.format(
            positions=positions_summary,
            market_state=market_state.to_llm_context(max_symbols=15),
        )

        try:
            return self._llm.analyze_json(
                system_prompt=SYSTEM_TRADE_ANALYST,
                user_prompt=user_prompt,
            )
        except Exception as e:
            logger.error("Position review failed: %s", e)
            return {"position_reviews": [], "portfolio_summary": f"Error: {e}"}
